### ISSUE TITLE
sticky Note On

### ISSUE THREAD

**Issue by amritgenius** [silveirago/OpenMIDIStomper#3]
Hello Gustavo, im using midiusb lib and am continously getting sticky "note on" every 1 or 2 hour of using midi controller. any idea? some days its work fine for 5 6 hours straightforward and some days every hour different note get stuck., sorry for bad english.

**Comment by silveirago** [comment]
MIDIUSB you mean using the OpenMIDIStomper or just the regular lib in another project?

**Comment by amritgenius** [comment]
thankyou for the follow up. it is just the regular lib in pretty much similar project. am using pro micro with usb c.

**Comment by silveirago** [comment]
Ah, then it could be a lot of things, but it never happened to me, so it's not a lib problem.
